version: '3'

tasks:
  test:
    desc: Run all tests
    cmds:
      - go test ./...

  coverage:
    desc: Run tests and generate coverage report
    cmds:
      - go test -coverprofile=coverage/coverage.out ./...
      - go tool cover -func=coverage/coverage.out
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html
      - echo "Coverage report saved to coverage.html"
