version: '3'

tasks:
  start:
    desc: Start the application
    aliases: [s]
    cmds:
      - go run cmd/server/*.go

  test:
    desc: Run all tests
    aliases: [t]
    cmds:
      - go test ./...

  test-verbose:
    desc: Run all tests with verbose output
    aliases: [tv]
    cmds:
      - go test -v ./...

  test-unit:
    desc: Run unit tests for specific package
    cmds:
      - go test -v {{.PACKAGE}}

  test-utils:
    desc: Test pagination utilities
    cmds:
      - go test -v ./internal/infrastructure/utils

  test-usecase:
    desc: Test all usecases
    cmds:
      - go test -v ./internal/usecase

  install-tools:
    desc: Install development tools
    cmds:
      - go install go.uber.org/mock/mockgen@latest
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

  generate-mocks:
    desc: Generate mocks for all interfaces
    aliases: [gen-mocks]
    cmds:
      # repository
      - mockgen -source=internal/domain/repository/article.go -destination=internal/domain/repository/mocks/mock_article_repository.go -package=mocks
      - mockgen -source=internal/domain/repository/category.go -destination=internal/domain/repository/mocks/mock_category_repository.go -package=mocks

      # usecase
      - mockgen -source=internal/usecase/get_articles.go -destination=internal/usecase/mocks/mock_get_articles_usecase.go -package=mocks
      - mockgen -source=internal/usecase/get_article_by_id.go -destination=internal/usecase/mocks/mock_get_article_by_id_usecase.go -package=mocks
      - mockgen -source=internal/usecase/get_categories.go -destination=internal/usecase/mocks/mock_get_categories_usecase.go -package=mocks
      - mockgen -source=internal/usecase/get_popular_articles.go -destination=internal/usecase/mocks/mock_get_popular_articles_usecase.go -package=mocks
      - mockgen -source=internal/usecase/get_latest_articles.go -destination=internal/usecase/mocks/mock_get_latest_articles_usecase.go -package=mocks
      - mockgen -source=internal/usecase/get_articles_by_category.go -destination=internal/usecase/mocks/mock_get_articles_by_category_usecase.go -package=mocks
      - mockgen -source=internal/usecase/get_zenn_articles.go -destination=internal/usecase/mocks/mock_get_zenn_articles_usecase.go -package=mocks

  generate-openapi:
    desc: Generate Go code from OpenAPI specification
    aliases: [gen-api]
    cmds:
      - oapi-codegen -config config/codegen.yaml schema/openapi.yaml

  coverage:
    desc: Run tests and generate coverage report
    aliases: [cov]
    cmds:
      - go test -coverprofile=coverage/coverage.out ./... -coverpkg=$(go list ./... | grep -v -E '/mocks|/openapi' | tr '\n' ',')
      - go tool cover -func=coverage/coverage.out
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html
      - echo "Coverage report saved to coverage.html"
