// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_categories.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_categories.go -destination=internal/usecase/mocks/mock_get_categories_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/kozennoki/nerine/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetCategoriesUsecase is a mock of GetCategoriesUsecase interface.
type MockGetCategoriesUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetCategoriesUsecaseMockRecorder
	isgomock struct{}
}

// MockGetCategoriesUsecaseMockRecorder is the mock recorder for MockGetCategoriesUsecase.
type MockGetCategoriesUsecaseMockRecorder struct {
	mock *MockGetCategoriesUsecase
}

// NewMockGetCategoriesUsecase creates a new mock instance.
func NewMockGetCategoriesUsecase(ctrl *gomock.Controller) *MockGetCategoriesUsecase {
	mock := &MockGetCategoriesUsecase{ctrl: ctrl}
	mock.recorder = &MockGetCategoriesUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetCategoriesUsecase) EXPECT() *MockGetCategoriesUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetCategoriesUsecase) Exec(ctx context.Context, input usecase.GetCategoriesUsecaseInput) (usecase.GetCategoriesUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, input)
	ret0, _ := ret[0].(usecase.GetCategoriesUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetCategoriesUsecaseMockRecorder) Exec(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetCategoriesUsecase)(nil).Exec), ctx, input)
}
