// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_zenn_articles.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_zenn_articles.go -destination=internal/usecase/mocks/mock_get_zenn_articles_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/kozennoki/nerine/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetZennArticlesUsecase is a mock of GetZennArticlesUsecase interface.
type MockGetZennArticlesUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetZennArticlesUsecaseMockRecorder
	isgomock struct{}
}

// MockGetZennArticlesUsecaseMockRecorder is the mock recorder for MockGetZennArticlesUsecase.
type MockGetZennArticlesUsecaseMockRecorder struct {
	mock *MockGetZennArticlesUsecase
}

// NewMockGetZennArticlesUsecase creates a new mock instance.
func NewMockGetZennArticlesUsecase(ctrl *gomock.Controller) *MockGetZennArticlesUsecase {
	mock := &MockGetZennArticlesUsecase{ctrl: ctrl}
	mock.recorder = &MockGetZennArticlesUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetZennArticlesUsecase) EXPECT() *MockGetZennArticlesUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetZennArticlesUsecase) Exec(ctx context.Context, input usecase.GetZennArticlesUsecaseInput) (usecase.GetZennArticlesUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, input)
	ret0, _ := ret[0].(usecase.GetZennArticlesUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetZennArticlesUsecaseMockRecorder) Exec(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetZennArticlesUsecase)(nil).Exec), ctx, input)
}
