// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_articles_by_category.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_articles_by_category.go -destination=internal/usecase/mocks/mock_get_articles_by_category_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/kozennoki/nerine/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetArticlesByCategoryUsecase is a mock of GetArticlesByCategoryUsecase interface.
type MockGetArticlesByCategoryUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetArticlesByCategoryUsecaseMockRecorder
	isgomock struct{}
}

// MockGetArticlesByCategoryUsecaseMockRecorder is the mock recorder for MockGetArticlesByCategoryUsecase.
type MockGetArticlesByCategoryUsecaseMockRecorder struct {
	mock *MockGetArticlesByCategoryUsecase
}

// NewMockGetArticlesByCategoryUsecase creates a new mock instance.
func NewMockGetArticlesByCategoryUsecase(ctrl *gomock.Controller) *MockGetArticlesByCategoryUsecase {
	mock := &MockGetArticlesByCategoryUsecase{ctrl: ctrl}
	mock.recorder = &MockGetArticlesByCategoryUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetArticlesByCategoryUsecase) EXPECT() *MockGetArticlesByCategoryUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetArticlesByCategoryUsecase) Exec(arg0 context.Context, arg1 usecase.GetArticlesByCategoryUsecaseInput) (usecase.GetArticlesByCategoryUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", arg0, arg1)
	ret0, _ := ret[0].(usecase.GetArticlesByCategoryUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetArticlesByCategoryUsecaseMockRecorder) Exec(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetArticlesByCategoryUsecase)(nil).Exec), arg0, arg1)
}
