// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_article_by_id.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_article_by_id.go -destination=internal/usecase/mocks/mock_get_article_by_id_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/kozennoki/nerine/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetArticleByIDUsecase is a mock of GetArticleByIDUsecase interface.
type MockGetArticleByIDUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetArticleByIDUsecaseMockRecorder
	isgomock struct{}
}

// MockGetArticleByIDUsecaseMockRecorder is the mock recorder for MockGetArticleByIDUsecase.
type MockGetArticleByIDUsecaseMockRecorder struct {
	mock *MockGetArticleByIDUsecase
}

// NewMockGetArticleByIDUsecase creates a new mock instance.
func NewMockGetArticleByIDUsecase(ctrl *gomock.Controller) *MockGetArticleByIDUsecase {
	mock := &MockGetArticleByIDUsecase{ctrl: ctrl}
	mock.recorder = &MockGetArticleByIDUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetArticleByIDUsecase) EXPECT() *MockGetArticleByIDUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetArticleByIDUsecase) Exec(ctx context.Context, input usecase.GetArticleByIDUsecaseInput) (usecase.GetArticleByIDUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, input)
	ret0, _ := ret[0].(usecase.GetArticleByIDUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetArticleByIDUsecaseMockRecorder) Exec(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetArticleByIDUsecase)(nil).Exec), ctx, input)
}
