// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_latest_articles.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_latest_articles.go -destination=internal/usecase/mocks/mock_get_latest_articles_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/kozennoki/nerine/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetLatestArticlesUsecase is a mock of GetLatestArticlesUsecase interface.
type MockGetLatestArticlesUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetLatestArticlesUsecaseMockRecorder
	isgomock struct{}
}

// MockGetLatestArticlesUsecaseMockRecorder is the mock recorder for MockGetLatestArticlesUsecase.
type MockGetLatestArticlesUsecaseMockRecorder struct {
	mock *MockGetLatestArticlesUsecase
}

// NewMockGetLatestArticlesUsecase creates a new mock instance.
func NewMockGetLatestArticlesUsecase(ctrl *gomock.Controller) *MockGetLatestArticlesUsecase {
	mock := &MockGetLatestArticlesUsecase{ctrl: ctrl}
	mock.recorder = &MockGetLatestArticlesUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetLatestArticlesUsecase) EXPECT() *MockGetLatestArticlesUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetLatestArticlesUsecase) Exec(arg0 context.Context, arg1 usecase.GetLatestArticlesUsecaseInput) (usecase.GetLatestArticlesUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", arg0, arg1)
	ret0, _ := ret[0].(usecase.GetLatestArticlesUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetLatestArticlesUsecaseMockRecorder) Exec(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetLatestArticlesUsecase)(nil).Exec), arg0, arg1)
}
