// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_popular_articles.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_popular_articles.go -destination=internal/usecase/mocks/mock_get_popular_articles_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/kozennoki/nerine/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetPopularArticlesUsecase is a mock of GetPopularArticlesUsecase interface.
type MockGetPopularArticlesUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetPopularArticlesUsecaseMockRecorder
	isgomock struct{}
}

// MockGetPopularArticlesUsecaseMockRecorder is the mock recorder for MockGetPopularArticlesUsecase.
type MockGetPopularArticlesUsecaseMockRecorder struct {
	mock *MockGetPopularArticlesUsecase
}

// NewMockGetPopularArticlesUsecase creates a new mock instance.
func NewMockGetPopularArticlesUsecase(ctrl *gomock.Controller) *MockGetPopularArticlesUsecase {
	mock := &MockGetPopularArticlesUsecase{ctrl: ctrl}
	mock.recorder = &MockGetPopularArticlesUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetPopularArticlesUsecase) EXPECT() *MockGetPopularArticlesUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetPopularArticlesUsecase) Exec(arg0 context.Context, arg1 usecase.GetPopularArticlesUsecaseInput) (usecase.GetPopularArticlesUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", arg0, arg1)
	ret0, _ := ret[0].(usecase.GetPopularArticlesUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetPopularArticlesUsecaseMockRecorder) Exec(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetPopularArticlesUsecase)(nil).Exec), arg0, arg1)
}
