// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/get_articles.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/get_articles.go -destination=internal/usecase/mocks/mock_get_articles_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/kozennoki/nerine/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockGetArticlesUsecase is a mock of GetArticlesUsecase interface.
type MockGetArticlesUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetArticlesUsecaseMockRecorder
	isgomock struct{}
}

// MockGetArticlesUsecaseMockRecorder is the mock recorder for MockGetArticlesUsecase.
type MockGetArticlesUsecaseMockRecorder struct {
	mock *MockGetArticlesUsecase
}

// NewMockGetArticlesUsecase creates a new mock instance.
func NewMockGetArticlesUsecase(ctrl *gomock.Controller) *MockGetArticlesUsecase {
	mock := &MockGetArticlesUsecase{ctrl: ctrl}
	mock.recorder = &MockGetArticlesUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetArticlesUsecase) EXPECT() *MockGetArticlesUsecaseMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockGetArticlesUsecase) Exec(ctx context.Context, input usecase.GetArticlesUsecaseInput) (usecase.GetArticlesUsecaseOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, input)
	ret0, _ := ret[0].(usecase.GetArticlesUsecaseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockGetArticlesUsecaseMockRecorder) Exec(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockGetArticlesUsecase)(nil).Exec), ctx, input)
}
