// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/article.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/article.go -destination=internal/domain/repository/mocks/mock_article_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/kozennoki/nerine/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockArticleRepository is a mock of ArticleRepository interface.
type MockArticleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepositoryMockRecorder
	isgomock struct{}
}

// MockArticleRepositoryMockRecorder is the mock recorder for MockArticleRepository.
type MockArticleRepositoryMockRecorder struct {
	mock *MockArticleRepository
}

// NewMockArticleRepository creates a new mock instance.
func NewMockArticleRepository(ctrl *gomock.Controller) *MockArticleRepository {
	mock := &MockArticleRepository{ctrl: ctrl}
	mock.recorder = &MockArticleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepository) EXPECT() *MockArticleRepositoryMockRecorder {
	return m.recorder
}

// CountArticles mocks base method.
func (m *MockArticleRepository) CountArticles(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountArticles", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountArticles indicates an expected call of CountArticles.
func (mr *MockArticleRepositoryMockRecorder) CountArticles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountArticles", reflect.TypeOf((*MockArticleRepository)(nil).CountArticles), ctx)
}

// CountArticlesByCategory mocks base method.
func (m *MockArticleRepository) CountArticlesByCategory(ctx context.Context, categorySlug string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountArticlesByCategory", ctx, categorySlug)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountArticlesByCategory indicates an expected call of CountArticlesByCategory.
func (mr *MockArticleRepositoryMockRecorder) CountArticlesByCategory(ctx, categorySlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountArticlesByCategory", reflect.TypeOf((*MockArticleRepository)(nil).CountArticlesByCategory), ctx, categorySlug)
}

// GetArticleByID mocks base method.
func (m *MockArticleRepository) GetArticleByID(ctx context.Context, id string) (*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleByID", ctx, id)
	ret0, _ := ret[0].(*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleByID indicates an expected call of GetArticleByID.
func (mr *MockArticleRepositoryMockRecorder) GetArticleByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleByID", reflect.TypeOf((*MockArticleRepository)(nil).GetArticleByID), ctx, id)
}

// GetArticles mocks base method.
func (m *MockArticleRepository) GetArticles(ctx context.Context, limit, offset int) ([]*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticles", ctx, limit, offset)
	ret0, _ := ret[0].([]*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticles indicates an expected call of GetArticles.
func (mr *MockArticleRepositoryMockRecorder) GetArticles(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticles", reflect.TypeOf((*MockArticleRepository)(nil).GetArticles), ctx, limit, offset)
}

// GetArticlesByCategory mocks base method.
func (m *MockArticleRepository) GetArticlesByCategory(ctx context.Context, categorySlug string, limit, offset int) ([]*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticlesByCategory", ctx, categorySlug, limit, offset)
	ret0, _ := ret[0].([]*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticlesByCategory indicates an expected call of GetArticlesByCategory.
func (mr *MockArticleRepositoryMockRecorder) GetArticlesByCategory(ctx, categorySlug, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticlesByCategory", reflect.TypeOf((*MockArticleRepository)(nil).GetArticlesByCategory), ctx, categorySlug, limit, offset)
}

// GetLatestArticles mocks base method.
func (m *MockArticleRepository) GetLatestArticles(ctx context.Context, limit int) ([]*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestArticles", ctx, limit)
	ret0, _ := ret[0].([]*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestArticles indicates an expected call of GetLatestArticles.
func (mr *MockArticleRepositoryMockRecorder) GetLatestArticles(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestArticles", reflect.TypeOf((*MockArticleRepository)(nil).GetLatestArticles), ctx, limit)
}

// GetPopularArticles mocks base method.
func (m *MockArticleRepository) GetPopularArticles(ctx context.Context, limit int) ([]*entity.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularArticles", ctx, limit)
	ret0, _ := ret[0].([]*entity.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularArticles indicates an expected call of GetPopularArticles.
func (mr *MockArticleRepositoryMockRecorder) GetPopularArticles(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularArticles", reflect.TypeOf((*MockArticleRepository)(nil).GetPopularArticles), ctx, limit)
}
